# .readthedocs.yaml
# Fichier de configuration pour Read the Docs
# Voir https://docs.readthedocs.io/en/stable/config-file/v2.html pour plus de détails

version: 2

# Spécifie l'environnement de construction
build:
  os: ubuntu-22.04 # Système d'exploitation pour la construction
  tools:
    python: "3.10" # Version de Python à utiliser (assurez-vous qu'elle est compatible avec votre projet)

# Spécifie la configuration Sphinx
sphinx:
  configuration: docs/source/conf.py # Chemin vers votre fichier conf.py

# Installe les dépendances nécessaires pour construire la documentation
# Cela inclut les dépendances de votre projet et les dépendances de documentation (Sphinx, thèmes, parsers)
python:
  install:
    - requirements: requirements.txt # Installe les dépendances de votre projet
    # Si vous avez des dépendances spécifiques pour la documentation (ex: sphinx, thèmes),
    # vous pouvez les lister ici ou les ajouter à requirements.txt
    # - method: pip
    #   path: .
    #   extra_requirements:
    #     - docs # Si vous avez une section [docs] dans setup.py

